### ISSUE TITLE
Error:     AttributeError: 'torch.device' object has no attribute 'lower'

### ISSUE THREAD

**Issue by gokriznastic** [eecn/Hyperspectral-Classification#1]
On running the following configuration:
`python main.py --model chen --dataset IndianPines --training_sample 0.3 --epoch 700 --cuda 0`

I get the error: `AttributeError: 'torch.device' object has no attribute 'lower'`

I have searched all over the Internet for this error, most of them are due to older versions of PyTorch. I am using v1.0. Can you please tell why this error might be happening?

**Comment by eecn** [comment]
Sorry for the late reply, this is because the device is a GPU error, I have changed the original code, you can look at the changed part. Because I was writing a paper in this area, some experiments were not added to the project .

**Comment by gokriznastic** [comment]
No worries. BTW I was able to get past this error by modifying the torchsummary.py. 
I replaced `torch.lower()` by `"cuda"`.

It worked fine after that. But I would recommend anyone doing this to make a virtual environment first (as specified in the README.md) and then do this so as to avoid modifying the original torchsummary.py.

**Comment by Lzyin** [comment]
> No worries. BTW I was able to get past this error by modifying the torchsummary.py.
> I replaced `torch.lower()` by `"cuda"`.
> 
> It worked fine after that. But I would recommend anyone doing this to make a virtual environment first (as specified in the README.md) and then do this so as to avoid modifying the original torchsummary.py.

excuse me， is replaced device = device.lower() by device = device.cuda() ？

**Comment by cjfghk5697** [comment]
I got same error when code is
```python
summary(model, (3, 224, 224), device=device)
```
And replace the code from 'device=device' to 'device=device.type'  
```python
summary(model, (3, 224, 224), device=device.type)
```

If modify the code as described above, it works fine.
