### ISSUE TITLE
关于1D-CNN模型特征抽取的问题

### ISSUE THREAD

**Issue by fhz-3722** [eecn/Hyperspectral-Classification#12]
您好，我使用你重现Hu(Deep Convolutional Neural Networks for Hyperspectral Image Classification, Wei Hu)的模型。将倒数第二层全连接层抽出作为特征向量，外接了一个SVM。问题出在SVM预测上，SVM总是将像元分类为样本最多的那一类中去。但是当使用softmax时，就可以正常预测了。
我使用的输入数据格式为(sample_pixels, bands, 1)，channels_last模式，目的是沿着光谱轴进行特征提取，是不是我输入维度不正确导致的？

**Comment by eecn** [comment]
可能是超参数设置不合理，理论上使用卷积网络提取的深度特征更具判别性，会促进传统分类器的分类性能。关于数据格式问题可以看一下dataset.py下的HyperX类。
