### ISSUE TITLE
Licensing issues and proper citation

### ISSUE THREAD

**Issue by nshaud** [eecn/Hyperspectral-Classification#16]
Hi @eecn ,

I'm the main author of the original code (https://github.com/nshaud/DeepHyperX/). It's fine that you forked the code however you removed the code license which is not okay. 

The code is dual-licensed (see [here](https://github.com/nshaud/DeepHyperX/blob/master/License)):
- for **research use**, the code from DeepHyperX is under GPLv3. Therefore your code for research should also be GPLv3 since it falls under modification/redistribution.
- for **commercial use**, the original code requires a license. The fork should respect this and appropriately reference the original authors.

Also, if you have done enhancements in the code that you feel can be useful for others, please consider submitting a pull request to the main project!

Thanks!

**Comment by eecn** [comment]
Thanks for your contribution.Sorry for the inconvenience, I will revise the relevant content as soon as possible.
