### ISSUE TITLE
您好！当执行代码使用cuda 1 卡时，出现报错

### ISSUE THREAD

**Issue by Lzyin** [eecn/Hyperspectral-Classification#17]
RuntimeError: Expected tensor for argument #1 'input' to have the same device as tensor for argument #2 'weight'; but device 0 does not equal 1 (while checking arguments for cudnn_convolution)
请问这是哪里出错了啊？

**Comment by eecn** [comment]
如果命令中心个输入是--cuda 1应该是没有问题的，检查一下显卡是否挂载了两个或以上显卡？

**Comment by Lzyin** [comment]
> 如果命令中心个输入是--cuda 1应该是没有问题的，检查一下显卡是否挂载了两个或以上显卡？

电脑上装有两个显卡 ， 当用cuda0 时 是没问题的  但是当用cuda1 也就是二卡时， 出现以上报错，请问是否是torchsummary.py 里面第53行：      dtype = torch.cuda.FloatTensor ，这条语句 默认执行cuda 0？

**Comment by Lzyin** [comment]
File "main.py", line 320, in <module>
    summary(model.to(hyperparams['device']), input.size()[1:])
  File "/home/ly/anaconda3/envs/pytorch1.7.0/lib/python3.6/site-packages/torchsummary/torchsummary.py", line 74, in summary
    model(*x)
  File "/home/ly/anaconda3/envs/pytorch1.7.0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/media/D/ly/code/Hyperspectral-Classification-master/models.py", line 679, in forward
    x = F.relu(self.conv1(x))
  File "/home/ly/anaconda3/envs/pytorch1.7.0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ly/anaconda3/envs/pytorch1.7.0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 573, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected tensor for argument #1 'input' to have the same device as tensor for argument #2 'weight'; but device 0 does not equal 1 (while checking arguments for cudnn_convolution)  这是报错轨迹

**Comment by eecn** [comment]
抱歉现在才回复你，这里应该是从train_loader得到的input数据默认在cuda 0，这里可以在summary前面加上这么一一条语句。
input = input.to(hyperparams['device'])

**Comment by 1165628028** [comment]
> 抱歉现在才回复你，这里应该是从train_loader得到的input数据默认在cuda 0，这里可以在summary前面加上这么一一条语句。
> input = input..to(hyperparams['device'])

请问是加在这里面吗： 
        with torch.no_grad(): # 作用是：反向传播不自动求导
            for input, _ in train_loader:
                break
            # summary(model.to(hyperparams['device']), input.size()[1:], device=hyperparams['device'])
            input = input.to(hyperparams['device'])
            summary(model.to(hyperparams['device']), input.size()[1:])
还是报这个错误。。。

**Comment by Lzyin** [comment]
> 抱歉现在才回复你，这里应该是从train_loader得到的input数据默认在cuda 0，这里可以在summary前面加上这么一一条语句。
> input = input..to(hyperparams['device'])

请问是加在这里吗：
        with torch.no_grad(): 
            for input, _ in train_loader:
                break
            # summary(model.to(hyperparams['device']), input.size()[1:], device=hyperparams['device'])
            input = input.to(hyperparams['device'])
            summary(model.to(hyperparams['device']), input.size()[1:])
还是报这个错误。。。

**Comment by 1165628028** [comment]
> 抱歉现在才回复你，这里应该是从train_loader得到的input数据默认在cuda 0，这里可以在summary前面加上这么一一条语句。
> input = input..to(hyperparams['device'])

我用cuda 0  跑 luo模型时，准确率非常低，其他模型准确率都比较正常，请问 是还需要预先对数据进行一些预处理吗

**Comment by Lzyin** [comment]
我用cuda 0  跑 luo模型时，准确率非常低，其他模型准确率都比较正常，请问 是还需要预先对数据进行一些预处理吗

**Comment by eecn** [comment]
> > 抱歉现在才回复你，这里应该是从train_loader得到的input数据默认在cuda 0，这里可以在summary前面加上这么一一条语句。
> > input = input..to(hyperparams['device'])
> 
> 请问是加在这里吗：
> with torch.no_grad():
> for input, _ in train_loader:
> break
> # summary(model.to(hyperparams['device']), input.size()[1:], device=hyperparams['device'])
> input = input.to(hyperparams['device'])
> summary(model.to(hyperparams['device']), input.size()[1:])
> 还是报这个错误。。。

抱歉，我手头上没有多卡调试。这个错误应该不难解决，你那边有多卡的话，可以输出一下变量和模型的位置查看一下，按照错误提示就是网络和参数不在同一个GPU设备。你可以参考一下这两个博客链接。
1. https://zhuanlan.zhihu.com/p/193118516
2. https://blog.csdn.net/weixin_43508499/article/details/104622495

**Comment by eecn** [comment]
> 我用cuda 0 跑 luo模型时，准确率非常低，其他模型准确率都比较正常，请问 是还需要预先对数据进行一些预处理吗

可以参考一下:https://ieeexplore.ieee.org/abstract/document/8455251

**Comment by Lzyin** [comment]
好的，非常谢谢您！

**Comment by Lzyin** [comment]
您好，换了一个torch-summary版本，已解决。十分感谢解答！
