### ISSUE TITLE
results did not show in visdom

### ISSUE THREAD

**Issue by sarahrajabazdeh** [eecn/Hyperspectral-Classification#2]
hi, 
i run the code via virtualenv,  i can see results such as confusion  matrix in my console but failed to visualize in visdom.
how can i fix that ?

**Comment by eecn** [comment]
You can refer to the Usage section of the README file.
1.You should  start a Visdom server with " python -m visdom.server " command,and it will return a URL address on the console.
2.Access the URL address on the browser.
After you run the different experiments,and you can see the visualizations on the browser.

**Comment by sarahrajabazdeh** [comment]
Thank you i change my browser . eveything is ok now! :).
