### ISSUE TITLE
I've Trained The Dataset...! But I'm unable to connect it to the Visdom Server. 

### ISSUE THREAD

**Issue by TirumalaManav** [eecn/Hyperspectral-Classification#25]
![Screenshot (20)](https://user-images.githubusercontent.com/98304013/234010115-c9335b5d-d779-48d1-be64-a2b3d8eae786.png)
![Screenshot (21)](https://user-images.githubusercontent.com/98304013/234010310-b7695730-13e2-4286-b046-74629841b691.png)
![Screenshot (22)](https://user-images.githubusercontent.com/98304013/234010411-47d2ae80-289e-497a-a052-d0c2bb31ae4a.png)

**Comment by TirumalaManav** [comment]
I've been getting this problem as well...! Could you perhaps assist me in identifying the mistake and pointing out where I am going wrong?

![Screenshot (23)](https://user-images.githubusercontent.com/98304013/234029176-de92a72f-f79e-4d71-a3d5-f5abf59f5c21.png)

**Comment by eecn** [comment]
Looks like a library version or configuration problem.

**Comment by num-doc** [comment]
I've been getting this problem as well...!   but  in request,txt, the version of visdom should be greater than 0.1.5, and my version is 0.2.4   
 
![image](https://github.com/eecn/Hyperspectral-Classification/assets/56705030/3b64b75e-3956-482e-b0cd-bc3597c0a791)
 it to work properly, I think this must be the specified version of visdom

**Comment by num-doc** [comment]
@eecn  What is your version of visdom ?

**Comment by eecn** [comment]
> @eecn What is your version of visdom ?

404 status, it doesn't look like it's a version issue, so please check again.
