### ISSUE TITLE
can not reach the accuracy in the paper

### ISSUE THREAD

**Issue by skxiaozi** [eecn/Hyperspectral-Classification#6]
I use the model "He" in your code, based on University of Pavia. The accuracy is 92.66%, which can reach the result 98.49% in the paper named "Multi-scale 3D deep convolutional neural network for hyperspectral image classification". Of course, I modified the code based on your answer in the previous answers.

**Comment by eecn** [comment]
The code of this project is not the original code of the paper author. There may be some differences in model initialization ,etwork structure ,etc.   
 **What's more**    
In my opinion, the experimental results of some papers are based on the initial random seed specified. Part of the  classification accuracy values is the best result from a single experiment,without cross validation or  given in the form of ”mean ± standard“ deviation from the perspective of statistics, which is used as a measurement of volatility.

**Comment by skxiaozi** [comment]
Thank you.
