### ISSUE TITLE
这个在划分训练集的时候每一类设置相同个数吗？

### ISSUE THREAD

**Issue by zhangjiahao1225** [eecn/Hyperspectral-Classification#7]
在训练集的测试集的划分上，我看是按照每一类像素点占据总像素点的比例来进行的。例如使用命令python main.py --model nn --dataset PaviaU --training_sample 0.1 --cuda 0，这里是在PaviaU数据集上，利用nn模型，其中采用百分之十作为数据集。
        我有一个想法：在这9类地物中，我每一类选取200个像素点进行训练，剩余的像素点作为测试集，于是我输入了python main.py --model nn --dataset PaviaU --training_sample 1800 --cuda 0，这样的命令，但是我发现这1800个像素点依然是按照每一类占据的比例来划分的，并不是每一类训练200个像素点。请问如果我想这样子做的话，应该输入什么命令呢，或者需要修改哪一部分的代码呢？希望可以得到您的指点。

**Comment by dongzhidong** [comment]
在参数里增加--sampling_mode  fixed 即可。

e.g.  python main.py --model nn --dataset PaviaU --training_sample 200 --sampling_mode  fixed --cuda 0

fixed抽样模式就是按类别抽取，你可以在utils.py文件sample_gt()函数里看到相关代码。

**Comment by dongzhidong** [comment]
> ```
>     在训练集的测试集的划分上，我看是按照每一类像素点占据总像素点的比例来进行的。例如使用命令python main.py --model nn --dataset PaviaU --training_sample 0.1 --cuda 0，这里是在PaviaU数据集上，利用nn模型，其中采用百分之十作为数据集。
>     我有一个想法：在这9类地物中，我每一类选取200个像素点进行训练，剩余的像素点作为测试集，于是我输入了python main.py --model nn --dataset PaviaU --training_sample 1800 --cuda 0，这样的命令，但是我发现这1800个像素点依然是按照每一类占据的比例来划分的，并不是每一类训练200个像素点。请问如果我想这样子做的话，应该输入什么命令呢，或者需要修改哪一部分的代码呢？希望可以得到您的指点。
> ```

在参数里增加--sampling_mode fixed 即可。

e.g. python main.py --model nn --dataset PaviaU --training_sample 200 --sampling_mode fixed --cuda 0

fixed抽样模式就是按类别抽取，你可以在utils.py文件sample_gt()函数里看到相关代码。

**Comment by yinlotus** [comment]
> 在参数里增加--sampling_mode fixed 即可。
> 
> e.g. python main.py --model nn --dataset PaviaU --training_sample 200 --sampling_mode fixed --cuda 0
> 
> fixed抽样模式就是按类别抽取，你可以在utils.py文件sample_gt()函数里看到相关代码。

打扰一下，这个工具箱里用到padding 的方法都有点问题，边缘像素分类结果全是黑色的背景，导致精度低，不知道有没有解决办法

**Comment by biscuit279** [comment]
我是新手菜鸡本科生，想把这个程序里面加一个主成分分析的功能降维后用2DCNN，改了好久没改好，编程基础太差了不知道要怎么改，又着急出成果。。。有没有大佬指点一些，可以有偿，微信biscuit279.球球了救救孩子吧~

**Comment by eecn** [comment]
> 我是新手菜鸡本科生，想把这个程序里面加一个主成分分析的功能降维后用2DCNN，改了好久没改好，编程基础太差了不知道要怎么改，又着急出成果。。。有没有大佬指点一些，可以有偿，微信biscuit279.球球了救救孩子吧~

 这个模型都使用了原始的高光谱数据，如果需要对数据进行预处理，建议可以使用sklearn进行处理，之后将数据加载到HyperX类中。

**Comment by eecn** [comment]
> > 在参数里增加--sampling_mode fixed 即可。
> > e.g. python main.py --model nn --dataset PaviaU --training_sample 200 --sampling_mode fixed --cuda 0
> > fixed抽样模式就是按类别抽取，你可以在utils.py文件sample_gt()函数里看到相关代码。
> 
> 打扰一下，这个工具箱里用到padding 的方法都有点问题，边缘像素分类结果全是黑色的背景，导致精度低，不知道有没有解决办法

这个问题实际上是深度网络处理的常用方案，只是说高光谱数据对padding更敏感一些<理论上和实际实验中我都试过>，torch、numpy等也有其他的padding方案可以试一试效果。
