### ISSUE TITLE
关于高光谱检测请教！

### ISSUE THREAD

**Issue by wangzyon** [eecn/Hyperspectral-Classification#8]
您好，看了您的开源项目，受益匪浅，谢谢！另外，请教下您，高光谱分类后，如何通过目标像素点输出目标边框和概率，高光谱目标检测一般是什么思路？

**Comment by eecn** [comment]
高光谱图像分类任务与光学图像的语义分割比较类似，是像素级的分类。检测的话应该是更接近自然图像的检测rcnn系列、yolo系列以及SSD等。
